// Document name parsing and Clerk-based authentication for the Hocuspocus
// editor service. Pure functions live here so they can be unit-tested
// without booting the server, opening a DB connection, or pulling Clerk
// network keys. `services/editor/server.ts` wires these into the runtime.

import {
    PROPOSAL_PREFIX,
    PROPOSAL_TEXT_SLUGS,
    REVIEW_FEEDBACK_PREFIX,
    UUID_RE,
    type ProposalTextSlug,
} from '../../src/lib/collaboration-documents.ts'

export type { ProposalTextSlug }

const UUID_LEN = 36

// Mirrors src/database/types.ts:StudyStatus. Duplicated rather than imported
// because that file is generated by kysely-codegen against the dev DB and
// pulling it in would drag the entire database/types graph into the editor
// service.
export type StudyStatus = 'APPROVED' | 'ARCHIVED' | 'CHANGE-REQUESTED' | 'DRAFT' | 'PENDING-REVIEW' | 'REJECTED'

// Mirrors src/lib/proposal-review.ts:SUBMITTED_REVIEW_STATUSES. Used to decide
// whether a `proposal-review-submitted` stateless event is plausible given the
// DB study status. Duplicated for the same reason.
const SUBMITTED_REVIEW_STATUSES: readonly StudyStatus[] = ['APPROVED', 'CHANGE-REQUESTED', 'REJECTED']

export type ParsedDocumentName =
    | { kind: 'review-feedback'; studyId: string }
    | { kind: 'proposal-fields'; studyId: string }
    | { kind: 'proposal-text'; studyId: string; slug: ProposalTextSlug }

export function parseDocumentName(name: string): ParsedDocumentName | null {
    if (name.startsWith(REVIEW_FEEDBACK_PREFIX)) {
        const studyId = name.slice(REVIEW_FEEDBACK_PREFIX.length)
        return UUID_RE.test(studyId) ? { kind: 'review-feedback', studyId } : null
    }

    if (!name.startsWith(PROPOSAL_PREFIX)) return null
    const remainder = name.slice(PROPOSAL_PREFIX.length)
    if (remainder.length < UUID_LEN + 2) return null

    const studyId = remainder.slice(0, UUID_LEN)
    if (!UUID_RE.test(studyId)) return null
    if (remainder[UUID_LEN] !== '-') return null
    const suffix = remainder.slice(UUID_LEN + 1)

    if (suffix === 'fields') return { kind: 'proposal-fields', studyId }

    if ((PROPOSAL_TEXT_SLUGS as readonly string[]).includes(suffix)) {
        return { kind: 'proposal-text', studyId, slug: suffix as ProposalTextSlug }
    }
    return null
}

// review-feedback-* documents are owned by the reviewing org (DO).
// proposal-* documents are owned by the submitting lab.
export function requiredOrgIdForDocument(
    parsed: ParsedDocumentName,
    study: { org_id: string; submitted_by_org_id: string },
): string {
    return parsed.kind === 'review-feedback' ? study.org_id : study.submitted_by_org_id
}

// Allowed study statuses for editing each document kind. Authentication
// rejects connections whose study has progressed past the editing window so
// stale clients (network glitch + reconnect) cannot keep mutating the
// persisted Yjs state after submission.
export function editableStatusForKind(kind: ParsedDocumentName['kind']): readonly StudyStatus[] {
    if (kind === 'review-feedback') return ['PENDING-REVIEW']
    return ['DRAFT', 'CHANGE-REQUESTED']
}

// Persist-time gate: returns true when the canonical Yjs state for this
// document is still allowed to advance. Connection-time auth (`authenticate`)
// covers new and reconnecting clients, but already-connected clients keep
// streaming Yjs updates between a status flip and their own kick-out. This
// gate is the second line of defense so post-flip writes never land in
// yjs_document. Safe to use as a silent skip because we already reject
// reconnects when status is non-editable, so no peer can fetch a pre-flip
// persisted state while other peers still hold post-flip in-memory state.
export async function shouldPersistDocument(parsed: ParsedDocumentName, db: Pick<DbQuery, 'query'>): Promise<boolean> {
    const row = await db.query<{ status: StudyStatus }>('SELECT status FROM study WHERE id = $1', [parsed.studyId])
    const status = row.rows[0]?.status
    if (!status) return false
    return editableStatusForKind(parsed.kind).includes(status)
}

export type EventType = 'proposal-submitted' | 'proposal-review-submitted'

export type StatelessSubmissionEvent = {
    type: EventType
    studyId: string
    submittedByName: string
    submittedByTabId: string
    /**
     * Clerk user id of the broadcasting client. The server compares this against
     * the authenticated `connection.context.user.clerkId` so a forged event from
     * an authorized but uninvolved collaborator is dropped before rebroadcast.
     */
    submittedByClerkId: string
}

// Server-side validation of stateless events the client emits via
// `provider.sendStateless(...)`. Mirrors the client SubmissionEvent shape but
// stays in this package so the editor service does not import from `src/`.
export function parseStatelessEvent(payload: unknown): StatelessSubmissionEvent | null {
    if (typeof payload !== 'string') return null

    let parsed: unknown
    try {
        parsed = JSON.parse(payload)
    } catch {
        return null
    }

    if (!parsed || typeof parsed !== 'object') return null
    const obj = parsed as Record<string, unknown>
    const { type, studyId, submittedByName, submittedByTabId, submittedByClerkId } = obj

    if (type !== 'proposal-submitted' && type !== 'proposal-review-submitted') return null
    if (typeof studyId !== 'string' || !UUID_RE.test(studyId)) return null
    if (typeof submittedByName !== 'string' || submittedByName.length === 0) return null
    if (typeof submittedByTabId !== 'string' || submittedByTabId.length === 0) return null
    if (typeof submittedByClerkId !== 'string' || submittedByClerkId.length === 0) return null

    return { type, studyId, submittedByName, submittedByTabId, submittedByClerkId }
}

// Returns true when the event type is appropriate for the document kind.
// `proposal-submitted` is broadcast on the proposal-fields doc by the lab
// submitter; `proposal-review-submitted` is broadcast on the review-feedback
// doc by the DO submitter. Anything else is suspicious and dropped.
export function isStatelessEventValidForDocument(event: StatelessSubmissionEvent, parsed: ParsedDocumentName): boolean {
    if (event.studyId !== parsed.studyId) return false
    if (event.type === 'proposal-submitted') return parsed.kind === 'proposal-fields'
    if (event.type === 'proposal-review-submitted') return parsed.kind === 'review-feedback'
    return false
}

// Strict consistency check before rebroadcasting a stateless event:
// 1. payload-vs-document-kind matches (handled by isStatelessEventValidForDocument)
// 2. sender's clerk id matches the authenticated user on this connection
// 3. DB study status is plausible for the claimed event type
//
// Without (2) and (3) any authorized collaborator could spoof a kick-out event
// and redirect the room without an actual submit.
export function assertStatelessEventConsistent(args: {
    event: StatelessSubmissionEvent
    parsed: ParsedDocumentName
    connectionUserClerkId: string
    studyStatus: StudyStatus
}): boolean {
    const { event, parsed, connectionUserClerkId, studyStatus } = args
    if (!isStatelessEventValidForDocument(event, parsed)) return false
    if (event.submittedByClerkId !== connectionUserClerkId) return false

    if (event.type === 'proposal-submitted') {
        return studyStatus === 'PENDING-REVIEW'
    }
    return SUBMITTED_REVIEW_STATUSES.includes(studyStatus)
}

// pg.Pool-compatible query interface (small surface so tests can pass a
// hand-rolled stub without depending on `pg`).
export type DbQuery = {
    query<T>(text: string, values?: unknown[]): Promise<{ rows: T[]; rowCount: number | null }>
}

export type VerifyTokenFn = (
    token: string,
    options: { jwtKey: string; secretKey?: string; authorizedParties?: string[] },
) => Promise<{ sub?: string | null }>

export interface AuthenticateDeps {
    db: DbQuery
    verifyToken: VerifyTokenFn
    jwtKey: string
    secretKey?: string
    authorizedParties?: string[]
    siAdminOrgSlug: string
}

export interface AuthenticatedContext {
    user: { id: string; clerkId: string }
}

// Stable codes that survive serialisation to the client via
// `onAuthenticationFailed.reason`. The wire format is `CODE: message` so the
// client can split on the first colon and dispatch on `code` rather than
// pattern-matching the message text.
export type AuthFailureCode =
    | 'MISSING_TOKEN'
    | 'INVALID_TOKEN'
    | 'UNRECOGNIZED_DOCUMENT'
    | 'USER_NOT_PROVISIONED'
    | 'STUDY_NOT_FOUND'
    | 'NO_MEMBERSHIP'
    | 'STUDY_NOT_EDITABLE'

export class AuthFailureError extends Error {
    readonly code: AuthFailureCode
    constructor(code: AuthFailureCode, message: string) {
        // The wire format `CODE: message` must be the Error.message because
        // Hocuspocus only forwards `err.message` to the client.
        super(`${code}: ${message}`)
        this.name = 'AuthFailureError'
        this.code = code
    }
}

export async function authenticate(
    args: { token: string | null | undefined; documentName: string },
    deps: AuthenticateDeps,
): Promise<AuthenticatedContext> {
    const { token, documentName } = args
    if (!token) throw new AuthFailureError('MISSING_TOKEN', 'missing token')

    const payload = await deps.verifyToken(token, {
        jwtKey: deps.jwtKey,
        secretKey: deps.secretKey,
        authorizedParties: deps.authorizedParties && deps.authorizedParties.length ? deps.authorizedParties : undefined,
    })
    const clerkUserId = payload.sub
    if (!clerkUserId) throw new AuthFailureError('INVALID_TOKEN', 'token has no subject')

    const parsed = parseDocumentName(documentName)
    if (!parsed) throw new AuthFailureError('UNRECOGNIZED_DOCUMENT', `unrecognized document "${documentName}"`)

    const userRow = await deps.db.query<{ id: string }>('SELECT id FROM "user" WHERE clerk_id = $1', [clerkUserId])
    const internalUserId = userRow.rows[0]?.id
    if (!internalUserId) throw new AuthFailureError('USER_NOT_PROVISIONED', 'user not provisioned')

    const studyRow = await deps.db.query<{ org_id: string; submitted_by_org_id: string; status: StudyStatus }>(
        'SELECT org_id, submitted_by_org_id, status FROM study WHERE id = $1',
        [parsed.studyId],
    )
    const study = studyRow.rows[0]
    if (!study) throw new AuthFailureError('STUDY_NOT_FOUND', 'study not found')

    const requiredOrgId = requiredOrgIdForDocument(parsed, study)

    // safe-insights admin bypass OR membership in the kind-required org.
    const accessRow = await deps.db.query(
        `SELECT 1
           FROM org_user ou
           JOIN org o ON o.id = ou.org_id
          WHERE ou.user_id = $1
            AND (
                (o.slug = $2 AND ou.is_admin = TRUE)
                OR ou.org_id = $3
            )
          LIMIT 1`,
        [internalUserId, deps.siAdminOrgSlug, requiredOrgId],
    )
    if (accessRow.rowCount === 0) throw new AuthFailureError('NO_MEMBERSHIP', 'no membership in study orgs')

    // Editable-status enforcement closes the stale-tab-reconnect window: a tab
    // that lost network during submit and reconnects post-flip would otherwise
    // keep mutating the persisted yjs_document. The client maps this code to
    // the kick-out flow (toast + redirect) rather than the generic "editor
    // unavailable" surface.
    const allowed = editableStatusForKind(parsed.kind)
    if (!allowed.includes(study.status)) {
        throw new AuthFailureError('STUDY_NOT_EDITABLE', `study is not editable (status: ${study.status})`)
    }

    return { user: { id: internalUserId, clerkId: clerkUserId } }
}
