version: 0.2

env:
    variables:
        REGION: us-east-1
        ACCOUNT_ID: 533267019973
        ECR_REPO_NAME: mgmt-app/r/sample-cicd-container

phases:
    pre_build:
        commands:
            - npm install -g npm
            - npm install

    build:
        commands:
            - npm run lint
            - echo Done.

artifacts:
    files:
        - '**/*'

reports:
    build-status-report:
        files:
            - '**/*'
        file-format: JUNITXML
