FROM node:22-bookworm AS base

WORKDIR /app


COPY package.json package-lock.json panda.config.ts ./

RUN npm install

RUN npx playwright install
RUN npx playwright install-deps

#COPY .gitignore .editorconfig next.config.mjs tsconfig.json kysely.config.ts .eslintrc.json .prettierrc.json .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED=1

# for deploying the build version

# RUN bun next build
# and
# CMD bun next start

# OR starting Next.js in development, comment above two lines and uncomment below line

CMD ["./bin/docker-dev-init"]
