services:
    dbgate:
        image: dbgate/dbgate
        restart: always
        container_name: dbgate
        networks:
            - management-app_mgmnt-app
        ports:
            - '3000:3000'
        volumes:
            - dbgate-data:/root/.dbgate
        environment:
            CONNECTIONS: bma

            LABEL_bma: Postgres
            SERVER_bma: postgres
            USER_bma: mgmnt
            PASSWORD_bma: mgmntpass
            PORT_bma: 5432
            ENGINE_bma: postgres@dbgate-plugin-postgres

networks:
    management-app_mgmnt-app:
        external: true

volumes:
    dbgate-data:
        driver: local
