/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type ResultFormat = 'SI_V1_ENCRYPT'

export type StudyJobStatus =
    | 'CODE-APPROVED'
    | 'CODE-REJECTED'
    | 'CODE-SUBMITTED'
    | 'ERRORED'
    | 'INITIATED'
    | 'PACKAGING'
    | 'PROVISIONING'
    | 'READY'
    | 'RESULTS-APPROVED'
    | 'RESULTS-REJECTED'
    | 'RUN-COMPLETE'
    | 'RUNNING'

export type StudyStatus = 'APPROVED' | 'ARCHIVED' | 'INITIATED' | 'PENDING-REVIEW' | 'REJECTED'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Member {
    created_at: Generated<Timestamp>
    email: string
    id: Generated<string>
    identifier: string
    name: string
    public_key: string
    updated_at: Generated<Timestamp>
}

export interface MemberUserPublicKey {
    created_at: Generated<Timestamp>
    fingerprint: string
    id: Generated<string>
    updated_at: Generated<Timestamp>
    user_id: string
    value: string
}

export interface Study {
    approved_at: Timestamp | null
    container_location: string
    created_at: Generated<Timestamp>
    data_sources: Generated<string[]>
    description: string
    id: Generated<string>
    irb_protocols: string | null
    member_id: string
    output_mime_type: string | null
    pi_name: string
    researcher_id: string
    status: Generated<StudyStatus>
    title: string
}

export interface StudyJob {
    completed_at: Timestamp | null
    created_at: Generated<Timestamp>
    id: Generated<string>
    result_format: ResultFormat
    results_path: string | null
    started_at: Timestamp | null
    status: Generated<StudyJobStatus>
    study_id: string
    uploaded_at: Timestamp | null
}

export interface DB {
    member: Member
    member_user_public_key: MemberUserPublicKey
    study: Study
    study_job: StudyJob
}
