/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type StudyRunStatus =
    | 'CODE-REJECTED'
    | 'CODE-SUBMITTED'
    | 'COMPLETED'
    | 'ERRORED'
    | 'INITIATED'
    | 'READY'
    | 'RESULTS-REJECTED'
    | 'RESULTS-REVIEW'
    | 'RUNNING'

export type StudyStatus = 'APPROVED' | 'ARCHIVED' | 'INITIATED' | 'REJECTED' | 'SUBMITTED'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Member {
    created_at: Generated<Timestamp>
    email: string
    id: Generated<string>
    identifier: string
    name: string
    public_key: string
    updated_at: Generated<Timestamp>
}

export interface Study {
    approved_at: Timestamp | null
    container_location: string
    created_at: Generated<Timestamp>
    data_sources: Generated<string[]>
    description: string
    id: Generated<string>
    irb_protocols: string | null
    member_id: string
    output_mime_type: string | null
    pi_name: string
    researcher_id: string
    status: Generated<StudyStatus>
    title: string
}

export interface StudyRun {
    completed_at: Timestamp | null
    created_at: Generated<Timestamp>
    file_count: number | null
    file_size: number | null
    id: Generated<string>
    results_path: string | null
    started_at: Timestamp | null
    status: Generated<StudyRunStatus>
    study_id: string
    uploaded_at: Timestamp | null
}

export interface DB {
    member: Member
    study: Study
    study_run: StudyRun
}
