/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export type StudyRunStatus = 'complete' | 'created' | 'pending' | 'rejected' | 'running'

export type StudyStatus = 'approved' | 'draft' | 'inactive' | 'proposal'

export type Timestamp = ColumnType<Date, Date | string>

export interface Member {
    created_at: Generated<Timestamp>
    email: string
    id: Generated<string>
    identifier: string
    name: string
    public_key: string
    updated_at: Generated<Timestamp>
}

export interface Study {
    approved_at: Timestamp | null
    container_location: string
    created_at: Generated<Timestamp>
    data_sources: Generated<string[]>
    description: string
    id: Generated<string>
    irb_protocols: string | null
    member_id: string
    output_mime_type: string | null
    pi_name: string
    researcher_id: string
    status: Generated<StudyStatus>
    title: string
    updated_at: Generated<Timestamp>
}

export interface StudyRun {
    code_review_path: string | null
    completed_at: Timestamp | null
    created_at: Generated<Timestamp>
    id: Generated<string>
    results_path: string | null
    started_at: Timestamp | null
    status: Generated<StudyRunStatus>
    study_id: string
    updated_at: Generated<Timestamp>
}

export interface DB {
    member: Member
    study: Study
    study_run: StudyRun
}
