name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize, ready_for_review]

# Explicit write permissions so the action can commit signatures and set statuses
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # JSON file committed by the action; do not pre-create this file
          path-to-signatures: 'signatures/version1/cla.json'
          # Full GitHub blob URL to CLA.md committed in this repository (required)
          path-to-document: 'https://github.com/safeinsights/management-app/blob/otter-303-test2/CLA.md'
          # Branch that stores the signatures file; MUST NOT be protected
          branch: 'otter-303-test2'
          # Exempt known users/bots from signing (optional)
          allowlist: 'dependabot[bot],bot*'
          # Optional customizations (uncomment to use)
          # create-file-commit-message: 'Create CLA signatures file'
          # signed-commit-message: '$contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          # custom-notsigned-prcomment: 'Please read and sign our CLA by replying with the signature phrase.'
          # custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          # custom-allsigned-prcomment: 'All contributors have signed the CLA.'
          # lock-pullrequest-aftermerge: true
          # suggest-recheck: true
          # use-dco-flag: false
